### ISSUE TITLE
jobsub_q prints errors

### ISSUE THREAD

**Issue by rlcee** [marcmengel/jobsub_lite#123]
jobsub_q prints errors (at least for rlc, on fifeutilgpvm01 with --devserver )
[rlc@fifeutilgpvm01 ~]$ rpm -q -a | grep jobsub
jobsub_dropbox_cleanup-1.2.4-1.x86_64
jobsub_lite-beta13-1.el7.x86_64

```
-- Failed to fetch ads from: <131.225.240.53:9615?addrs=131.225.240.53-9615&alias=jobsub03.fnal.gov&noUDP&sock=schedd_2728_c273> : jobsub03.fnal.gov
AUTHENTICATE:1003:Failed to authenticate with any method

-- Failed to fetch ads from: <131.225.161.104:9615?addrs=131.225.161.104-9615&alias=jobsub02.fnal.gov&noUDP&sock=schedd_3341_3a01> : jobsub02.fnal.gov
AUTHENTICATE:1003:Failed to authenticate with any method

-- Failed to fetch ads from: <131.225.161.91:9618?addrs=131.225.161.91-9618&alias=gpce03.fnal.gov&noUDP&sock=schedd_3397_a34f> : gpce03.fnal.gov
AUTHENTICATE:1003:Failed to authenticate with any method

```

**Comment by marcmengel** [comment]
This is because we have several schedd nodes (i.e. jobsub02, jobsub03) that aren't configured to 
accept tokens (yet). These errors will go away once we roll token support out more completely.

Also, jobsub_q doesn't accept "--devserver" even in the current (jobsub_client) code. 
We *could* make the new one accept it... but you can do:
`jobsub_q -name jobsubdevpgmv01.fnal.gov`
(in jobsub_lite) to see just that schedd.

**Comment by marcmengel** [comment]
Or rather` jobsub_q -G group -name jobsubdevgpvm01.fnal.gov`  -- you still need -G
