### ISSUE TITLE
Wrap lines for jobsub_q output if possible

### ISSUE THREAD

**Issue by shreyb** [marcmengel/jobsub_lite#173]
@rlcee uncovered this in testing:

"the print from jobsub_q ends at the terminal edge, so I see
rlc ID: 57107013 12/5 07:39 _ 1 _ _ 1 57107
but if I direct it into a file, the true line is:
rlc ID: 57107013 12/5 07:39 _ _ _ _ 1 57107013.0
meanwhile the final lines wrap:
Total for query: 31 jobs; 18 completed, 0 removed, 2 idle, 1 running, 10 held, 0 suspended
I'd prefer all lines wrap so I'm not silently missing text."

---@shreyb Comment:
I'm not sure how much we can do about this, since we're pulling this from condor_q, but it's worth a look

**Comment by rlcee** [comment]
It seems like there is probably a terminal control character embedded in the text,
which could be filtered out.

________________________________________
From: Shreyas Bhat ***@***.***>
Sent: Monday, December 5, 2022 10:56 AM
To: marcmengel/jobsub_lite
Cc: Raymond L Culbertson; Mention
Subject: [marcmengel/jobsub_lite] Wrap lines for jobsub_q output if possible (Issue #173)

@rlcee<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rlcee&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=ruz2yEXZpw6go9xSylH6SA&m=yBhMQ86ngZDIi_JfjQvOvE0nPWBk2B8Dhzqr_tLTwnOjivKQAR2UBCdDTVkgCAZh&s=jb7Xu_ZOBaDdpkt5p2dgDTwElZYFkMOW1OpaSLwXCy4&e=> uncovered this in testing:

"the print from jobsub_q ends at the terminal edge, so I see
rlc ID: 57107013 12/5 07:39 _ 1 _ _ 1 57107
but if I direct it into a file, the true line is:
rlc ID: 57107013 12/5 07:39 _ _ _ _ 1 57107013.0
meanwhile the final lines wrap:
Total for query: 31 jobs; 18 completed, 0 removed, 2 idle, 1 running, 10 held, 0 suspended
I'd prefer all lines wrap so I'm not silently missing text."

***@***.***<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shreyb&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=ruz2yEXZpw6go9xSylH6SA&m=yBhMQ86ngZDIi_JfjQvOvE0nPWBk2B8Dhzqr_tLTwnOjivKQAR2UBCdDTVkgCAZh&s=A6ldkh99Dxqx52oSmB_cr12tQv8iilagVx5XlqoJdNc&e=> Comment:
I'm not sure how much we can do about this, since we're pulling this from condor_q, but it's worth a look

**Comment by marcmengel** [comment]
So the default output for jobsub_q is now like the old jobsub's, and does not truncate due to screen width. 
However if you specify output format options (-autoformat, -batch, -dag, etc.), you get the underlying 
condor_q behaviour on various formats which truncates at the screen width.   You can avoid the 
truncation by piping the output through "cat" -- if the immediate output is not a terminal, it doesn't truncate to the 
screen width...

**Comment by marcmengel** [comment]
So I am closing this as fixed in #175, with the caveat that specifying condor_q output format options can default you back to the condor_q default behavior, which is to truncate output at the screen width.
