### ISSUE TITLE
Create reduced token scope for jobs

### ISSUE THREAD

**Issue by marcmengel** [marcmengel/jobsub_lite#195]
So the conclusion at the token task force meeting was that we should be issuing stronger tokens by default (i.e. with storage.modify scope, etc.) and then jobsub should prune out various permissions for the tokens that will be put in our jobs, via the `*_oauth_permissions` functionality of the condor submit files.  

We should filter these permissions/token scopes by default, and have an option 
(i.e. --keep-scope=storage.modify) to *not* filter the token scope for the job.

**Comment by retzkek** [comment]
I don't think a filter is sufficient. We should be encouraging users to be more explicit and restrictive with scopes, especially when e.g. production has `storage.modify:/experiment`, they should instead restrict that to e.g. `storage.modify:/experiment/persistent/run2/reco/campaign36/` or whatever. 

What about something like `--need-modify /experiment/persistent/run2/reco/campaign36`? Make them tell jobsub _where_ they need to modify, and then we could not only restrict the scopes but then make sure their token will allow that (rather than waiting for the 10,000 jobs to fail). We could even have a similar `--need-read` check.

**Comment by shreyb** [comment]
So @retzkek, @marcmengel , and I had an offline discussion about this, and this is the summary of steps needed here:

1.  In FERRY/token issuer, configuration changes need to be made so that tokens are created with scope `storage.modify` only on areas that they can already write to (scope `storage.create`).  
2. jobsub_lite should, by default, request a token that gives a reduced scope.  If a user provides no flags, we should give them `storage.read` and `storage.create` scopes on the areas their original token allows for.  This will be accomplished by running `htgettoken` to get the original token, reading it with `decode_token.sh`, and then populating the condor JDF template with only the `read` and `create` scopes.
3. If a user wants the `storage.modify` scope, they must request it explicitly with a flag.  I propose we have two flags that accomplish this:  
    1. `--need-modify DCACHE-PATH`.  As @retzkek suggested, it's a common enough scope, and laid out in [this document](https://zenodo.org/record/3460258#.Y6DjjeLMKBQ), so we can give it a helpful name.  
    2. `--need-scope SCOPE`.  In our discussion, @marcmengel brought up that we may need to support generic scopes for future storage elements that may not yet be defined.  We should allow this by allowing users to provide a custom scope.
4. In both of the above cases, we need to check the scope provided against the scopes in the user's original token.  If the user's original token has the relevant `storage.modify` or custom scope on a path that is a parent-path to the requested path in the flag, then we will write the requested scope into the condor JDF template.  e.g. if a user passes `--need-modify /mu2e/persistent/run2/reco/campaign36` and their original token has `storage.modify:/mu2e/persistent`, we will pass on the requested scope.  Otherwise, we should provide a helpful error message saying why they can't do it.


If we're worried about the timeframe for implementing this, @retzkek suggested that we provide these flags as no-ops, train the users to use them, and implement all the steps when we have time to do so.  This way, we won't be breaking any workflows post-go-live.

**Comment by marcmengel** [comment]
I have a draft in the "weakened tokens" branch, making notes here 'cause I'm not sure if I'm going to make
much more progress on this before the holidays...

I'm getting the submit file I expect, with:
`use_oauth_services = mu2e
mu2e_oauth_permissions = "storage.read:/mu2e compute.create compute.read compute
.cancel compute.modify storage.create:/mu2e/scratch/users/mengel storage.modify:
/mu2e/scratch/users/mengel/outdir"
`

but the job is in an "idle/running/idle/running' cycle, and the shadow log says:

`12/20/22 16:18:14 (2783.0) (2195871): CONDOR_getcreds: ERROR reading contents of /var/lib/condor/oauth_credentials/mengel/mu2e.use
`

Also, condor_vault_storer is stomping on my current token with one with the limited scope,
so I can't do two launches in a row with restricted scope, because we already pruned it the first time...
So with this turned on we're going to need to copy the token and set BEARER_TOKEN_FILE beforee
submitting, so we don't scribble on our original token with the restricted one.

**Comment by DrDaveD** [comment]
Would it be better for condor_vault_storer to be extended to have an option or environment variable to choose the storage location?

**Comment by marcmengel** [comment]
I think that's fine.  
I've pushed a commit onto "weakened_tokens" that de-fangs the weakened tokens; all we have to do is uncomment
the lines in the templates later.  I'll make a pull request on that version so we have one with all the options, and an easy
change (undo 1 commit) to enable it when the vault-credmon is fixed.

**Comment by DrDaveD** [comment]
@marcmengel what exactly do you mean here by vault-credmon being fixed?  Do you have a feature request for condor-credmon-vault along the lines of what I suggested?

**Comment by marcmengel** [comment]
@DrDaveD By vault-credmon being fixed I mean including the system default CA file in the urllib calls, which I believe you've already put in upstream?

**Comment by DrDaveD** [comment]
Yes it is already in upstream.  Judging by the tags on the [PR](https://github.com/htcondor/htcondor/pull/995), it should be in versions 10.0.1 and 10.2.0 which coincidentally were released [today](https://htcondor.org/downloads/htcondor.html).

**Comment by marcmengel** [comment]
Implemented in #202 .
